version: "3.1"
services:
    sonarr:
      image: lscr.io/linuxserver/sonarr:latest
      container_name: sonarr
      environment:
        - PUID=13001
        - PGID=13000
        - UMASK=002
        - TZ=EST
      volumes:
        - /ServarrSuite/config/sonarr-config:/config
        - /mnt/samsung870/data:/data
      ports:
          - "8989:8989"
      restart: unless-stopped

    radarr:
      image: lscr.io/linuxserver/radarr:latest
      container_name: radarr
      environment:
        - PUID=13002
        - PGID=13000
        - UMASK=002
        - TZ=EST
      volumes:
        - /ServarrSuite/config/radarr-config:/config
        - /mnt/samsung870/data:/data
      ports:
        - "7878:7878"
      restart: unless-stopped

    lidarr:
      image: lscr.io/linuxserver/lidarr:latest
      container_name: lidarr
      environment:
        - PUID=13003
        - PGID=13000
        - UMASK=002
        - TZ=EST
      volumes:
        - /ServarrSuite/config/lidarr-config:/config
        - /mnt/samsung870/data:/data
      ports:
        - "8686:8686"
      restart: unless-stopped
      
    readarr:
      image: lscr.io/linuxserver/readarr:develop
      container_name: readarr
      environment:
        - PUID=13004
        - PGID=13000
        - UMASK=002
        - TZ=EST
      volumes:
        - /ServarrSuite/config/readarr-config:/config
        - /mnt/samsung870/data:/data
      ports:
        - "8787:8787"
      restart: unless-stopped

    prowlarr:
      image: lscr.io/linuxserver/prowlarr:develop
      container_name: prowlarr
      environment:
        - PUID=13006
        - PGID=13000
        - UMASK=002
        - TZ=EST
      volumes:
        - /ServarrSuite/config/prowlarr-config:/config
        - /mnt/samsung870/data:/data
      ports:
        - "9696:9696"
      restart: unless-stopped
    
    jellyfin:
      image: lscr.io/linuxserver/jellyfin:latest
      container_name: jellyfin
      environment:
        - PUID=1000
        - PGID=13000
        - UMASK=002
        - TZ=EST
      volumes:
        - /ServarrSuite/config/jellyfin-config:/config
        - /mnt/samsung870/data/media:/data/media
      ports:
        - "9000:9000"
      restart: unless-stopped

    jellyseerr:
      image: fallenbagel/jellyseerr:latest
      container_name: jellyseerr
      environment:
        - PUID=13012
        - PGID=13012
        - UMASK=002
        - LOG_LEVEL=debug
        - TZ=EST
      volumes:
        - /ServarrSuite/config:/app/config
        - /mnt/samsung870/data/media:/data/media
      ports:
        - 5055:5055
      restart: unless-stopped

    qbittorrent:
      image: lscr.io/linuxserver/qbittorrent:latest
      container_name: qbittorrent
      environment:
        - PUID=13007
        - PGID=13000
        - UMASK=002
        - TZ=EST
        - WEBUI_PORT=8080
      volumes:
        - /ServarrSuite/config/qbittorrent-config:/config
        - /mnt/samsung870/data/torrents:/data/torrents
      ports:
        - "8080:8080"
        - "6881:6881"
        - "6881:6881/udp"
      restart: unless-stopped

    gluetun:
    image: qmcgaw/gluetun
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=expressvpn
      - OPENVPN_USER= njwk7851veqb6q3yhvpzgmpj
      - OPENVPN_PASSWORD= uvuea6ymbh2lfccykwygu8ov
      - SERVER_COUNTRIES=Netherlands, USA
    restart: unless-stopped