version: "3.1"
services:
    gluetun:
      image: qmcgaw/gluetun:latest
      container_name: gluetun
      cap_add:
        - NET_ADMIN
      network_mode: bridge
      ports:
        - 8888:8888/tcp # HTTP proxy
        - 8388:8388/tcp # Shadowsocks
        - 8388:8388/udp # Shadowsocks
        - 8001:8001/tcp # Built-in HTTP control server
        - 7878:7878 # radarr
        - 8989:8989 # sonarr
        - 8686:8686 # lidarr
        - 8787:8787 # readarr
        - 9696:9696 # prowlarr
        - 5055:5055 # jellyseer
        - 5299:5299 # Lazylibrarian
        - 8080:8080 # qbittorrent
        - 6881:6881 # qbittorrent
        - 6881:6881/udp # qbittorrent
      environment:
        - VPN_SERVICE_PROVIDER=expressvpn
        - OPENVPN_USER= njwk7851veqb6q3yhvpzgmpj
        - OPENVPN_PASSWORD= uvuea6ymbh2lfccykwygu8ov
        - SERVER_COUNTRIES= USA
        - HTTPPROXY=on
        - PUID=1000
        - PGID=1000
        - TZ=EST
      volumes:
        - /ServarrSuite/config/gluetun-config:/config
      restart: unless-stopped

    sonarr:
      image: lscr.io/linuxserver/sonarr:latest
      container_name: sonarr
      network_mode: "service:gluetun"
      environment:
        - PUID=13001
        - PGID=13000
        - UMASK=002
        - TZ=EST
      volumes:
        - /ServarrSuite/config/sonarr-config:/config
        - /mnt/samsung870/data:/data
      restart: unless-stopped

    radarr:
      image: lscr.io/linuxserver/radarr:latest
      container_name: radarr
      network_mode: "service:gluetun"
      environment:
        - PUID=13002
        - PGID=13000
        - UMASK=002
        - TZ=EST
      volumes:
        - /ServarrSuite/config/radarr-config:/config
        - /mnt/samsung870/data:/data
      restart: unless-stopped

    lidarr:
      image: lscr.io/linuxserver/lidarr:latest
      container_name: lidarr
      network_mode: "service:gluetun"
      environment:
        - PUID=13003
        - PGID=13000
        - UMASK=002
        - TZ=EST
      volumes:
        - /ServarrSuite/config/lidarr-config:/config
        - /mnt/samsung870/data:/data
      restart: unless-stopped
      
    readarr:
      image: lscr.io/linuxserver/readarr:develop
      container_name: readarr
      network_mode: "service:gluetun"
      environment:
        - PUID=13004
        - PGID=13000
        - UMASK=002
        - TZ=EST
      volumes:
        - /ServarrSuite/config/readarr-config:/config
        - /mnt/samsung870/data:/data
      restart: unless-stopped

    lazylibrarian:
      image: ghcr.io/linuxserver/lazylibrarian:latest
      container_name: lazylibrarian
      network_mode: "service:gluetun"
      environment:
        - PUID=13013
        - PGID=13000
        - TZ=EST
      volumes:
        - /ServarrSuite/config/lazylibrarian-config:/config
        - /mnt/samsung870/data:/data
      restart: unless-stopped

    prowlarr:
      image: lscr.io/linuxserver/prowlarr:develop
      container_name: prowlarr
      network_mode: "service:gluetun"
      environment:
        - PUID=13006
        - PGID=13000
        - UMASK=002
        - TZ=EST
      volumes:
        - /ServarrSuite/config/prowlarr-config:/config
        - /mnt/samsung870/data:/data
      restart: unless-stopped

    qbittorrent:
      image: lscr.io/linuxserver/qbittorrent:latest
      container_name: qbittorrent
      network_mode: "service:gluetun"
      environment:
        - PUID=13007
        - PGID=13000
        - UMASK=002
        - TZ=EST
        - WEBUI_PORT=8080
      volumes:
        - /ServarrSuite/config/qbittorrent-config:/config
        - /mnt/samsung870/data/torrents:/data/torrents
      restart: unless-stopped
          
    jellyfin:
      image: lscr.io/linuxserver/jellyfin:latest
      container_name: jellyfin
      environment:
        - PUID=1000
        - PGID=13000
        - UMASK=002
        - TZ=EST
      volumes:
        - /ServarrSuite/config/jellyfin-config:/config
        - /mnt/samsung870/data/media:/data/media
      ports:
        - 8096:8096
      restart: unless-stopped

    jellyseerr:
      image: fallenbagel/jellyseerr:latest
      container_name: jellyseerr
      network_mode: "service:gluetun"
      environment:
        - PUID=13012
        - PGID=13012
        - UMASK=002
        - LOG_LEVEL=debug
        - TZ=EST
      volumes:
        - /ServarrSuite/config:/app/config
        - /mnt/samsung870/data/media:/data/media
      restart: unless-stopped